# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Checkout/Build/Format/Lint/Codecov

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        id: pnpm-install
        with:
          version: 8
      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT
      - name: Setup pnpm cache
        uses: actions/cache@v3
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-
      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
  format:
    needs: build
    runs-on: ubuntu-latest
    name: Format
    steps:
      - name: Format
        run: pnpm format
  lint:
    needs: build
    runs-on: ubuntu-latest
    name: Lint
    steps:
      - name: Lint
        run: pnpm lint
  test:
    needs: build
    runs-on: ubuntu-latest
    name: Test
    steps:
      - name: Vitest
        run: pnpm test:unit
  coverage:
    needs: build
    runs-on: ubuntu-latest
    name: Coverage
    steps:
      - name: Coverage
        run: pnpm coverage
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
