name: Today Crons

on:
  schedule:
    - cron: '*/10 * * * *'

jobs:
  http-request:
    runs-on: ubuntu-latest

    steps:
      - name: Daily Durations
        run: |
          curl https://codingstats.cesarmejia.com/api/cron/wakatime/durations/today
      - name: Daily Durations By Language
        run: |
          curl https://codingstats.cesarmejia.com/api/cron/wakatime/durations-by-language/today
      - name: Daily Summaries
        run: |
          curl https://codingstats.cesarmejia.com/api/cron/wakatime/summaries/today
      - name: Daily Project Summaries
        run: |
          curl https://codingstats.cesarmejia.com/api/cron/wakatime/project-summaries/today
