name: Cron for Daily Durations

on:
  schedule:
    - cron: '*/10 * * * *'

jobs:
  http-request:
    runs-on: ubuntu-latest

    steps:
      - name: Send HTTP Request
        run: |
          curl https://codingstats.vercel.app/api/cron/wakatime/durations
