name: Yesterday Crons

on:
  schedule:
    - cron: '01 01 * * *'

jobs:
  http-request:
    runs-on: ubuntu-latest

    steps:
      - name: Yesterday Duration
        run: |
          curl https://codingstats.vercel.app/api/cron/wakatime/durations
      - name: Yesterday Durations By Language
        run: |
          curl https://codingstats.vercel.app/api/cron/wakatime/durations-by-language
      - name: Yesterday Summaries
        run: |
          curl https://codingstats.vercel.app/api/cron/wakatime/summaries
      - name: Yesterday Project Summaries
        run: |
          curl https://codingstats.vercel.app/api/cron/wakatime/project-summaries
